const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE : 'CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',

    //admin position manage
    FETCH_POSITION_START : 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS : 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED : 'FETCH_POSITION_FAILED',

    // admin gender manage 
    FETCH_GENDER_START : 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS : 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED : 'FETCH_GENDER_FAILED',

    // admin role manage
    FETCH_ROLE_START : 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS : 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED : 'FETCH_ROLE_FAILED',

    // handle create new user from UserRedux Form
    FETCH_CREATE_NEW_USER_START : 'FETCH_CREATE_NEW_USER_START',
    FETCH_CREATE_NEW_USER_SUCCESS  : 'FETCH_CREATE_NEW_USER_SUCCESS',
    FETCH_CREATE_NEW_USER_FAILED : 'FETCH_CREATE_NEW_USER_FAILED',

    // handle get all user by redux 
    FETCH_ALL_USER_SUCCESS : 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED : 'FETCH_ALL_USER_FAILED',

    // handle delete user by redux
    DELETE_USER_SUCCESS : 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED : 'DELETE_USER_FAILED',

    EDIT_USER_SUCCESS : 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED : 'EDIT_USER_FAILED',

    // homepage //
    //top doctor 
    GET_TOP_DOCTOR_SUCCESS : 'GET_TOP_DOCTOR_SUCCESS',
    GET_TOP_DOCTOR_FAILED : 'GET_TOP_DOCTOR_FAILED',

    // CO SO VAT CHAT MEDICAL FACILITIES
    GET_ALL_MEDICAL_FACILITIES : 'GET_ALL_MEDICAL_FACILITIES',
    GET_ALL_MEDICAL_FACILITIES_FAILED : 'GET_ALL_MEDICAL_FACILITIES_FAILED',
    // new

    GET_ALL_DOCTOR_SUCCESS : 'GET_ALL_DOCTOR_SUCCESS',
    GET_ALL_DOCTOR_FAILED : 'GET_ALL_DOCTOR_FAILED',

    SAVE_DOCTOR_SUCCESS : 'SAVE_DOCTOR_SUCCESS',
    SAVE_DOCTOR_FAILED : 'SAVE_DOCTOR_FAILED',

    GET_ALL_CODE_SCHEDULE_TIME_SUCCESS : 'GET_ALL_CODE_SCHEDULE_TIME_SUCCESS',
    GET_ALL_CODE_SCHEDULE_TIME_FAILED : 'GET_ALL_CODE_SCHEDULE_TIME_FAILED',

    FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS : 'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFOR_FAILED : 'FETCH_REQUIRED_DOCTOR_INFOR_FAILED',

    // handle create new clinic from ClinicManage 
    CREATE_NEW_CLINIC_ACTION_START : ' CREATE_NEW_CLINIC_ACTION_START',
    CREATE_NEW_CLINIC_ACTION_SUCCESS  : 'CREATE_NEW_CLINIC_ACTION_SUCCESS',
    CREATE_NEW_CLINIC_ACTION_FAILED : 'CREATE_NEW_CLINIC_ACTION_FAILED ',

    GET_ALL_CLINIC_SUCCESS : 'GET_ALL_CLINIC_SUCCESS ', 
    GET_ALL_CLINIC_FAILED : '  GET_ALL_CLINIC_FAILED',

    UPDATE_CLINIC_SUCCESS : 'UPDATE_CLINIC_SUCCESS ', 
    UPDATE_CLINIC_FAILED : 'UPDATE_CLINIC_FAILED',

    // CHUYEN KHOA
    GET_ALL_CHUYEN_KHOA_SUCCESS : 'GET_ALL_CHUYEN_KHOA_SUCCESS ', 
    GET_ALL_CHUYEN_KHOA_FAILED : '  GET_ALL_CHUYEN_KHOA_FAILED',

    GET_LIST_CHUYEN_KHOA_SUCCESS : 'GET_LIST_CHUYEN_KHOA_SUCCESS',
    GET_LIST_CHUYEN_KHOA_FAILED : 'GET_LIST_CHUYEN_KHOA_FAILED'

});

export default actionTypes;